INSERT INTO users (username, password, email,role_id)
VALUES

('idit', '123jsd4', 'idit@gmail.com', 1),
('Meital Rozental', 'jdke834', 'meital@gmail.com', 1),
('Yosef Rozental', 'jejej433', 'yosef@gmail.com', 1),
('Atlas Air', 'hees437', 'atlasair@gmail.com', 2),
('American Airlines', 'sdgf234', 'americanairlines@gmail.com', 2),
('Egyptair', 'zxcv123', 'egyptair@gmail.com', 2),
('Air India', 'qwer456', 'airindia@gmail.com', 2),
('Air Nigeria', 'rtyu789', 'airnigeria@gmail.com', 2),
('Air Sudan', 'tyui123', 'airsudan@gmail.com', 2),
('Air Europa', 'cvbn456', 'aireuropa@gmail.com', 2),
('Air New Zealand', 'bnms789', 'airnewzealand@gmail.com', 2),
('Air France', 'hjkl123', 'airfrance@gmail.com', 2),
('Air China', 'mlk0456', 'airchina@gmail.com', 2),
('Vietnam Airlines', 'cvbn678', 'vietnamairlines@gmail.com', 2),
('Turkish Airlines', 'opqr789', 'thy@gmail.com', 2),
('Ankor Air', 'asdf012', 'angkorair@gmail.com', 2),
('Bahrain Air', 'zxcv345', 'bahrainair@gmail.com', 2),
('Garuda Indonesia', 'qwer678', 'garudaindonesia@gmail.com', 2),
('JetAsia', 'rtyu901', 'jetasia@gmail.com', 2),
('South African Airways', 'cvbn234', 'flysaa@gmail.com', 2),
('South Sudan Airways', 'bnms567', 'sudanairlines@gmail.com', 2),
('Cathay Pacific', 'hjkl890', 'cathaypacific@gmail.com', 2),
('Lufthansa', 'mlk1234', 'lufthansa@gmail.com', 2),
('Royal Air Maroc', 'opqr567', 'royalairmaroc@gmail.com', 2),
('Nigeria Airways', 'asdf789', 'nigeriaairways@gmail.com', 2),
('United Airlines', 'rtyu345', 'unitedairlines@gmail.com', 2),
('El Al', 'A1B2C3D4', 'elal@gmail.com', 2),
('Arkay', 'E5F6G7H8', 'arkay@gmail.com', 2),
('Israir', 'I9J0K1L2', 'israir@gmail.com', 2),
('San Door', 'M3N4O5P6', 'sandoor@gmail.com', 2),
('aya aviation', 'Q7R8S9T0', 'aya_aviation@gmail.com', 2),
('Air Haifa', 'U1V2W3X4', 'air_haifa@gmail.com', 2),
('meof_aviation', 'Y5Z6A7B8','meof_aviation@gmail.com', 2),
('Ait Aviation','C9D0E1F2','ait_aviation@gmail.com',2),
('Admin michael rozental', 'gsgj632', 'admin_michael_rozental@gmail.com', 3);

